In [1]:
import pandas as pd
import numpy as np

In [2]:
med_price_list = [55,25,75,40,90]

In [3]:
med_price_arr = np.array(med_price_list)

In [4]:
med_price_arr

array([55, 25, 75, 40, 90])

In [5]:
series_list = pd.Series(med_price_list)

In [6]:
series_arr = pd.Series(med_price_arr)

In [7]:
print(series_list)
print(series_arr)

0    55
1    25
2    75
3    40
4    90
dtype: int64
0    55
1    25
2    75
3    40
4    90
dtype: int32


In [8]:
med_price_list_labeled = pd.Series(med_price_list, index = ['Omeprazole','Azithromycin','Metformin','Ibuprofen','Cetirizine'])

In [9]:
print(med_price_list_labeled)

Omeprazole      55
Azithromycin    25
Metformin       75
Ibuprofen       40
Cetirizine      90
dtype: int64


In [10]:
med_price_list_updated = med_price_list_labeled + 2.5

In [11]:
print(med_price_list_updated)

Omeprazole      57.5
Azithromycin    27.5
Metformin       77.5
Ibuprofen       42.5
Cetirizine      92.5
dtype: float64


In [12]:
new_price_list = [75, 45.5, 100, 50, 80]

In [13]:
new_price_list_labeled = pd.Series(new_price_list, index = ['Omeprazole','Azithromycin','Metformin','Ibuprofen','Cetirizine'])

In [14]:
print(new_price_list_labeled)

Omeprazole       75.0
Azithromycin     45.5
Metformin       100.0
Ibuprofen        50.0
Cetirizine       80.0
dtype: float64


In [15]:
print('Difference between the new price and old price - ')
print(new_price_list_labeled - med_price_list_updated)

Difference between the new price and old price - 
Omeprazole      17.5
Azithromycin    18.0
Metformin       22.5
Ibuprofen        7.5
Cetirizine     -12.5
dtype: float64


In [16]:
student = ['Mary','Peter','Susan','Toby','Vishal']

In [17]:
df1 = pd.DataFrame(student, columns =['Student'])

In [18]:
print(df1)

  Student
0    Mary
1   Peter
2   Susan
3    Toby
4  Vishal


In [20]:
# defining another list
grades = ['B-','A+','A-', 'B+', 'C']

# creating the dataframe using a dictionary
df2 = pd.DataFrame({'Student':student,'Grade':grades})
df2

Student Grade
0    Mary    B-
1   Peter    A+
2   Susan    A-
3    Toby    B+
4  Vishal     C

In [24]:
year = pd.Series([2012,2013,2014,2015,2016,2017,2018])
energy_consumption = pd.Series([2152,2196,2217,2194,2172,2180,2258])
df3 = pd.DataFrame({'Year':year, 'Energy Consumption(Mtoe)':energy_consumption})
df3

Year  Energy Consumption(Mtoe)
0  2012                      2152
1  2013                      2196
2  2014                      2217
3  2015                      2194
4  2016                      2172
5  2017                      2180
6  2018                      2258

In [25]:
df4 = pd.DataFrame(np.random.randn(5,2), columns = ['Trial 1','Trial 2'])
df4

Trial 1   Trial 2
0 -1.218111 -1.537175
1  0.481381  1.900863
2 -1.395238  1.168815
3  1.289690 -1.148281
4 -0.651158  0.491002

In [26]:
operators = ['AT&T','Verizon','T-Mobile US','US Cellular']
revenue = [171.76,128.29,68.4,4.04]
telecom = pd.Series(revenue, index = operators)
telecom

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

In [28]:
telecom[0:3]

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [29]:
telecom[-2]

68.4

In [31]:
telecom[[0,2,3]]

AT&T           171.76
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

In [32]:
telecom['AT&T']

171.76

In [33]:
telecom[:'T-Mobile US']

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [34]:
telecom[['AT&T','US Cellular','Verizon']]

AT&T           171.76
US Cellular      4.04
Verizon        128.29
dtype: float64

In [36]:
store_data = pd.DataFrame({'Customer Id':['CustID00','CustID01','CustID02','CustID03','CustID04'],
                           'Location':['Chicago','Boston','Seattle','San Francisco','Austin'],
                           'Gender':['M','M','F','M','F'],
                           'Type':['Electronics','Food & Beverages','Food & Beverages','Medicine','Beauty'],
                           'Quantity':[1,3,4,2,1],
                           'Total Bill':[100,75,125,50,80]})
store_data

Customer Id       Location Gender              Type  Quantity  Total Bill
0    CustID00        Chicago      M       Electronics         1         100
1    CustID01         Boston      M  Food & Beverages         3          75
2    CustID02        Seattle      F  Food & Beverages         4         125
3    CustID03  San Francisco      M          Medicine         2          50
4    CustID04         Austin      F            Beauty         1          80

In [42]:
store_data[:1]

Customer Id Location Gender         Type  Quantity  Total Bill
0    CustID00  Chicago      M  Electronics         1         100

In [43]:
store_data['Location']

0          Chicago
1           Boston
2          Seattle
3    San Francisco
4           Austin
Name: Location, dtype: object

In [44]:
store_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Customer Id  5 non-null      object
 1   Location     5 non-null      object
 2   Gender       5 non-null      object
 3   Type         5 non-null      object
 4   Quantity     5 non-null      int64 
 5   Total Bill   5 non-null      int64 
dtypes: int64(2), object(4)
memory usage: 372.0+ bytes


In [45]:
store_data[::2]

Customer Id Location Gender              Type  Quantity  Total Bill
0    CustID00  Chicago      M       Electronics         1         100
2    CustID02  Seattle      F  Food & Beverages         4         125
4    CustID04   Austin      F            Beauty         1          80

In [47]:
store_data[::-1]

Customer Id       Location Gender              Type  Quantity  Total Bill
4    CustID04         Austin      F            Beauty         1          80
3    CustID03  San Francisco      M          Medicine         2          50
2    CustID02        Seattle      F  Food & Beverages         4         125
1    CustID01         Boston      M  Food & Beverages         3          75
0    CustID00        Chicago      M       Electronics         1         100

In [48]:
store_data.loc[1]

Customer Id            CustID01
Location                 Boston
Gender                        M
Type           Food & Beverages
Quantity                      3
Total Bill                   75
Name: 1, dtype: object

In [212]:
store_data.loc[[1,2],['Location','Type']]

Location              Type
1   Boston  Food & Beverages
2  Seattle  Food & Beverages

In [62]:
store_data.iloc[[1,4],[0,2]]

Customer Id Gender
1    CustID01      M
4    CustID04      F

In [61]:
store_data.iloc[:4, 0:4]

Customer Id       Location Gender              Type
0    CustID00        Chicago      M       Electronics
1    CustID01         Boston      M  Food & Beverages
2    CustID02        Seattle      F  Food & Beverages
3    CustID03  San Francisco      M          Medicine

In [63]:
store_data.iloc[[1,4],['location','type']]

IndexError: .iloc requires numeric indexers, got ['location' 'type']

In [64]:
store_data

Customer Id       Location Gender              Type  Quantity  Total Bill
0    CustID00        Chicago      M       Electronics         1         100
1    CustID01         Boston      M  Food & Beverages         3          75
2    CustID02        Seattle      F  Food & Beverages         4         125
3    CustID03  San Francisco      M          Medicine         2          50
4    CustID04         Austin      F            Beauty         1          80

In [69]:
print(store_data.loc[4,'Type'])
store_data.loc[4,'Type']='Electronics'
print(store_data)

Electronics
  Customer Id       Location Gender              Type  Quantity  Total Bill
0    CustID00        Chicago      M       Electronics         1         100
1    CustID01         Boston      M  Food & Beverages         3          75
2    CustID02        Seattle      F  Food & Beverages         4         125
3    CustID03  San Francisco      M          Medicine         2          50
4    CustID04         Austin      F       Electronics         1          80


In [70]:
store_data.iloc[4,3]='Beauty'

In [71]:
store_data

Customer Id       Location Gender              Type  Quantity  Total Bill
0    CustID00        Chicago      M       Electronics         1         100
1    CustID01         Boston      M  Food & Beverages         3          75
2    CustID02        Seattle      F  Food & Beverages         4         125
3    CustID03  San Francisco      M          Medicine         2          50
4    CustID04         Austin      F            Beauty         1          80

In [72]:
store_data['Quantity']>1

0    False
1     True
2     True
3     True
4    False
Name: Quantity, dtype: bool

In [73]:
store_data.loc[store_data['Quantity']>1]

Customer Id       Location Gender              Type  Quantity  Total Bill
1    CustID01         Boston      M  Food & Beverages         3          75
2    CustID02        Seattle      F  Food & Beverages         4         125
3    CustID03  San Francisco      M          Medicine         2          50

In [74]:
store_data

Customer Id       Location Gender              Type  Quantity  Total Bill
0    CustID00        Chicago      M       Electronics         1         100
1    CustID01         Boston      M  Food & Beverages         3          75
2    CustID02        Seattle      F  Food & Beverages         4         125
3    CustID03  San Francisco      M          Medicine         2          50
4    CustID04         Austin      F            Beauty         1          80

In [77]:
store_data['Rating'] = [2,5,3,4,4]

In [84]:
store_data.drop('rating', axis=1, inplace = True)

In [85]:
store_data

Customer Id       Location Gender              Type  Quantity  Total Bill  \
0    CustID00        Chicago      M       Electronics         1         100   
1    CustID01         Boston      M  Food & Beverages         3          75   
2    CustID02        Seattle      F  Food & Beverages         4         125   
3    CustID03  San Francisco      M          Medicine         2          50   
4    CustID04         Austin      F            Beauty         1          80   

   Rating  
0       2  
1       5  
2       3  
3       4  
4       4

In [86]:
new_store_data = store_data.copy()

In [87]:
new_store_data

Customer Id       Location Gender              Type  Quantity  Total Bill  \
0    CustID00        Chicago      M       Electronics         1         100   
1    CustID01         Boston      M  Food & Beverages         3          75   
2    CustID02        Seattle      F  Food & Beverages         4         125   
3    CustID03  San Francisco      M          Medicine         2          50   
4    CustID04         Austin      F            Beauty         1          80   

   Rating  
0       2  
1       5  
2       3  
3       4  
4       4

In [91]:
new_store_data.drop(['Location','Rating'],axis = 1,inplace=True)

In [92]:
new_store_data

Customer Id Gender              Type  Quantity  Total Bill
0    CustID00      M       Electronics         1         100
1    CustID01      M  Food & Beverages         3          75
2    CustID02      F  Food & Beverages         4         125
3    CustID03      M          Medicine         2          50
4    CustID04      F            Beauty         1          80

In [93]:
store_data

Customer Id       Location Gender              Type  Quantity  Total Bill  \
0    CustID00        Chicago      M       Electronics         1         100   
1    CustID01         Boston      M  Food & Beverages         3          75   
2    CustID02        Seattle      F  Food & Beverages         4         125   
3    CustID03  San Francisco      M          Medicine         2          50   
4    CustID04         Austin      F            Beauty         1          80   

   Rating  
0       2  
1       5  
2       3  
3       4  
4       4

In [94]:
store_data.drop(1, axis=0)

Customer Id       Location Gender              Type  Quantity  Total Bill  \
0    CustID00        Chicago      M       Electronics         1         100   
2    CustID02        Seattle      F  Food & Beverages         4         125   
3    CustID03  San Francisco      M          Medicine         2          50   
4    CustID04         Austin      F            Beauty         1          80   

   Rating  
0       2  
2       3  
3       4  
4       4

In [95]:
store_data

Customer Id       Location Gender              Type  Quantity  Total Bill  \
0    CustID00        Chicago      M       Electronics         1         100   
1    CustID01         Boston      M  Food & Beverages         3          75   
2    CustID02        Seattle      F  Food & Beverages         4         125   
3    CustID03  San Francisco      M          Medicine         2          50   
4    CustID04         Austin      F            Beauty         1          80   

   Rating  
0       2  
1       5  
2       3  
3       4  
4       4

In [96]:
store_data_new =store_data.drop(1,axis = 0)

In [97]:
store_data_new

Customer Id       Location Gender              Type  Quantity  Total Bill  \
0    CustID00        Chicago      M       Electronics         1         100   
2    CustID02        Seattle      F  Food & Beverages         4         125   
3    CustID03  San Francisco      M          Medicine         2          50   
4    CustID04         Austin      F            Beauty         1          80   

   Rating  
0       2  
2       3  
3       4  
4       4

In [101]:
store_data_new.reset_index(inplace = True)

In [102]:
store_data_new

index Customer Id       Location Gender              Type  Quantity  \
0      0    CustID00        Chicago      M       Electronics         1   
1      2    CustID02        Seattle      F  Food & Beverages         4   
2      3    CustID03  San Francisco      M          Medicine         2   
3      4    CustID04         Austin      F            Beauty         1   

   Total Bill  Rating  
0         100       2  
1         125       3  
2          50       4  
3          80       4

In [105]:
store_data_new.drop(['index'], axis=1, inplace=True)

In [106]:
store_data_new

Customer Id       Location Gender              Type  Quantity  Total Bill  \
0    CustID00        Chicago      M       Electronics         1         100   
1    CustID02        Seattle      F  Food & Beverages         4         125   
2    CustID03  San Francisco      M          Medicine         2          50   
3    CustID04         Austin      F            Beauty         1          80   

   Rating  
0       2  
1       3  
2       4  
3       4

In [111]:
data_cust = pd.DataFrame({'CustomerID':['101','102','103','104'],
                          'Category':['Medium','Medium','High','Low'],
                          'First Visit':['yes','no','yes','yes'],
                          'Sales':[123,52,214,663]}, index=[0,1,2,3])

In [125]:
data_cust_new = pd.DataFrame({'CustomerID':['101','102','103','105'],
                              'Distance':[12,9,44,21],
                              'Sales':[123,214,663,331]},index=[4,5,6,7])

In [126]:
data_cust

CustomerID Category First Visit  Sales
0        101   Medium         yes    123
1        102   Medium          no     52
2        103     High         yes    214
3        104      Low         yes    663

In [127]:
data_cust_new

CustomerID  Distance  Sales
4        101        12    123
5        102         9    214
6        103        44    663
7        105        21    331

In [128]:
pd.concat([data_cust, data_cust_new], axis=0)

CustomerID Category First Visit  Sales  Distance
0        101   Medium         yes    123       NaN
1        102   Medium          no     52       NaN
2        103     High         yes    214       NaN
3        104      Low         yes    663       NaN
4        101      NaN         NaN    123      12.0
5        102      NaN         NaN    214       9.0
6        103      NaN         NaN    663      44.0
7        105      NaN         NaN    331      21.0

In [129]:
pd.merge(data_cust, data_cust_new, how='outer',on='CustomerID')

CustomerID Category First Visit  Sales_x  Distance  Sales_y
0        101   Medium         yes    123.0      12.0    123.0
1        102   Medium          no     52.0       9.0    214.0
2        103     High         yes    214.0      44.0    663.0
3        104      Low         yes    663.0       NaN      NaN
4        105      NaN         NaN      NaN      21.0    331.0

In [130]:
pd.merge(data_cust, data_cust_new, how='inner', on='CustomerID')

CustomerID Category First Visit  Sales_x  Distance  Sales_y
0        101   Medium         yes      123        12      123
1        102   Medium          no       52         9      214
2        103     High         yes      214        44      663

In [131]:
pd.merge(data_cust, data_cust_new, how='right', on='CustomerID')

CustomerID Category First Visit  Sales_x  Distance  Sales_y
0        101   Medium         yes    123.0        12      123
1        102   Medium          no     52.0         9      214
2        103     High         yes    214.0        44      663
3        105      NaN         NaN      NaN        21      331

In [132]:
pd.merge(data_cust, data_cust_new, how='left', on='CustomerID')

CustomerID Category First Visit  Sales_x  Distance  Sales_y
0        101   Medium         yes      123      12.0    123.0
1        102   Medium          no       52       9.0    214.0
2        103     High         yes      214      44.0    663.0
3        104      Low         yes      663       NaN      NaN

In [134]:
data_quarters = pd.DataFrame({'Q1':[101,102,103],
                              'Q2':[201,202,203]},
                              index = ['I0','I1','I2'])

In [135]:
data_quarters_new = pd.DataFrame({'Q3':[301,302,303],
                                  'Q4':[401,402,403]},
                                  index = ['I0','I1','I2'])

In [136]:
data_quarters

Q1   Q2
I0  101  201
I1  102  202
I2  103  203

In [137]:
data_quarters_new

Q3   Q4
I0  301  401
I1  302  402
I2  303  403

In [140]:
data_quarters.join(data_quarters_new, how='outer')

Q1   Q2   Q3   Q4
I0  101  201  301  401
I1  102  202  302  402
I2  103  203  303  403

In [141]:
data_quarters

Q1   Q2
I0  101  201
I1  102  202
I2  103  203

In [142]:
data = pd.read_csv('StockData (1).csv')

In [144]:
data.head()

stock        date    price
0  AAPL  08-02-2013  67.8542
1  AAPL  11-02-2013  68.5614
2  AAPL  12-02-2013  66.8428
3  AAPL  13-02-2013  66.7156
4  AAPL  14-02-2013  66.6556

In [145]:
data.to_csv('StockDataSaved.csv')

In [146]:
data.to_excel('StockDataSavedExcel.xlsx')

In [147]:
data.tail()

stock        date  price
5031   ZTS  01-02-2018  77.82
5032   ZTS  02-02-2018  76.78
5033   ZTS  05-02-2018  73.83
5034   ZTS  06-02-2018  73.27
5035   ZTS  07-02-2018  73.86

In [148]:
data.shape

(5036, 3)

In [149]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   stock   5036 non-null   object 
 1   date    5036 non-null   object 
 2   price   5036 non-null   float64
dtypes: float64(1), object(2)
memory usage: 118.2+ KB


In [150]:
data['price'].min()

28.4

In [151]:
data.min()

stock          AAPL
date     01-02-2016
price          28.4
dtype: object

In [152]:
data['price'].max()

179.26

In [153]:
data.max()

stock           ZTS
date     31-12-2015
price        179.26
dtype: object

In [154]:
data['stock'].unique()

array(['AAPL', 'SNI', 'TJX', 'ZTS'], dtype=object)

In [155]:
data['stock'].value_counts()

AAPL    1259
SNI     1259
TJX     1259
ZTS     1259
Name: stock, dtype: int64

In [157]:
data['stock'].value_counts(normalize=True)

AAPL    0.25
SNI     0.25
TJX     0.25
ZTS     0.25
Name: stock, dtype: float64

In [158]:
data['price'].mean()

73.05702966640192

In [167]:
data['stock'].mode()

0    AAPL
1     SNI
2     TJX
3     ZTS
Name: stock, dtype: object

In [168]:
data['price'].mode()

0    74.59
Name: price, dtype: float64

In [172]:
data.groupby(['stock'])['price'].mean()

stock
AAPL    109.066698
SNI      71.319206
TJX      66.743566
ZTS      45.098648
Name: price, dtype: float64

In [173]:
data.groupby(['stock'])['price'].median()

stock
AAPL    109.01
SNI      72.31
TJX      68.85
ZTS      45.62
Name: price, dtype: float64

In [174]:
def profit(s):
    return s + s*0.1

In [175]:
data['price'].apply(profit)

0       74.63962
1       75.41754
2       73.52708
3       73.38716
4       73.32116
          ...   
5031    85.60200
5032    84.45800
5033    81.21300
5034    80.59700
5035    81.24600
Name: price, Length: 5036, dtype: float64

In [176]:
data.head()

stock        date    price
0  AAPL  08-02-2013  67.8542
1  AAPL  11-02-2013  68.5614
2  AAPL  12-02-2013  66.8428
3  AAPL  13-02-2013  66.7156
4  AAPL  14-02-2013  66.6556

In [177]:
data['new_price'] =data['price'].apply(profit)
data.head()

stock        date    price  new_price
0  AAPL  08-02-2013  67.8542   74.63962
1  AAPL  11-02-2013  68.5614   75.41754
2  AAPL  12-02-2013  66.8428   73.52708
3  AAPL  13-02-2013  66.7156   73.38716
4  AAPL  14-02-2013  66.6556   73.32116

In [178]:
data

stock        date    price  new_price
0     AAPL  08-02-2013  67.8542   74.63962
1     AAPL  11-02-2013  68.5614   75.41754
2     AAPL  12-02-2013  66.8428   73.52708
3     AAPL  13-02-2013  66.7156   73.38716
4     AAPL  14-02-2013  66.6556   73.32116
...    ...         ...      ...        ...
5031   ZTS  01-02-2018  77.8200   85.60200
5032   ZTS  02-02-2018  76.7800   84.45800
5033   ZTS  05-02-2018  73.8300   81.21300
5034   ZTS  06-02-2018  73.2700   80.59700
5035   ZTS  07-02-2018  73.8600   81.24600

[5036 rows x 4 columns]

In [179]:
data.sort_values(by='new_price', ascending=False)

stock        date   price  new_price
1244  AAPL  18-01-2018  179.26    197.186
1243  AAPL  17-01-2018  179.10    197.010
1245  AAPL  19-01-2018  178.46    196.306
1241  AAPL  12-01-2018  177.09    194.799
1247  AAPL  23-01-2018  177.04    194.744
...    ...         ...     ...        ...
4076   ZTS  17-04-2014   28.60     31.460
4074   ZTS  15-04-2014   28.55     31.405
4075   ZTS  16-04-2014   28.53     31.383
4073   ZTS  14-04-2014   28.48     31.328
4072   ZTS  11-04-2014   28.40     31.240

[5036 rows x 4 columns]

In [180]:
data

stock        date    price  new_price
0     AAPL  08-02-2013  67.8542   74.63962
1     AAPL  11-02-2013  68.5614   75.41754
2     AAPL  12-02-2013  66.8428   73.52708
3     AAPL  13-02-2013  66.7156   73.38716
4     AAPL  14-02-2013  66.6556   73.32116
...    ...         ...      ...        ...
5031   ZTS  01-02-2018  77.8200   85.60200
5032   ZTS  02-02-2018  76.7800   84.45800
5033   ZTS  05-02-2018  73.8300   81.21300
5034   ZTS  06-02-2018  73.2700   80.59700
5035   ZTS  07-02-2018  73.8600   81.24600

[5036 rows x 4 columns]

In [183]:
path = "StockData (1).csv"

In [184]:
data2 = pd.read_csv(path)

In [185]:
data2

stock        date    price
0     AAPL  08-02-2013  67.8542
1     AAPL  11-02-2013  68.5614
2     AAPL  12-02-2013  66.8428
3     AAPL  13-02-2013  66.7156
4     AAPL  14-02-2013  66.6556
...    ...         ...      ...
5031   ZTS  01-02-2018  77.8200
5032   ZTS  02-02-2018  76.7800
5033   ZTS  05-02-2018  73.8300
5034   ZTS  06-02-2018  73.2700
5035   ZTS  07-02-2018  73.8600

[5036 rows x 3 columns]

In [186]:
data2['date'] = pd.to_datetime(data2['date'], dayfirst=True)

In [188]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   stock   5036 non-null   object        
 1   date    5036 non-null   datetime64[ns]
 2   price   5036 non-null   float64       
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 118.2+ KB


In [189]:
data2.head

<bound method NDFrame.head of      stock       date    price
0     AAPL 2013-02-08  67.8542
1     AAPL 2013-02-11  68.5614
2     AAPL 2013-02-12  66.8428
3     AAPL 2013-02-13  66.7156
4     AAPL 2013-02-14  66.6556
...    ...        ...      ...
5031   ZTS 2018-02-01  77.8200
5032   ZTS 2018-02-02  76.7800
5033   ZTS 2018-02-05  73.8300
5034   ZTS 2018-02-06  73.2700
5035   ZTS 2018-02-07  73.8600

[5036 rows x 3 columns]>

In [190]:
data2['date'].dt.strftime('%m/%d/%y')

0       02/08/13
1       02/11/13
2       02/12/13
3       02/13/13
4       02/14/13
          ...   
5031    02/01/18
5032    02/02/18
5033    02/05/18
5034    02/06/18
5035    02/07/18
Name: date, Length: 5036, dtype: object

In [191]:
data2['date'].dt.strftime('%m-%d-%y')

0       02-08-13
1       02-11-13
2       02-12-13
3       02-13-13
4       02-14-13
          ...   
5031    02-01-18
5032    02-02-18
5033    02-05-18
5034    02-06-18
5035    02-07-18
Name: date, Length: 5036, dtype: object

In [192]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))

In [193]:
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [194]:
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [199]:
demo_array = np.array([1,2,3,4,5,6,7,8,9,10])

In [200]:
demo_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [201]:
demo_array[0:7]=5

In [202]:
demo_array

array([ 5,  5,  5,  5,  5,  5,  5,  8,  9, 10])

In [203]:
import numpy as np
demo_array = np.arange(0,10)
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [204]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5